and back to ulimit -S -m because there is no -v option at least on OpenBSD

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -17,12 +17,12 @@ MAXMEM=2097152 # 2GB
 MAXTIME=60
 for file in tests/*.scm
 do
-   (ulimit -S -t $MAXTIME; ulimit -S -v $MAXMEM; $@ -q < $file 2>&1 | diff $file.ok - >> $LOG || echo "ERROR: $file" >> $LOG; /bin/echo -n " o") &
+   (ulimit -S -t $MAXTIME; ulimit -S -m $MAXMEM; $@ -q < $file 2>&1 | diff $file.ok - >> $LOG || echo "ERROR: $file" >> $LOG; /bin/echo -n " o") &
 done
 
 for file in tests/*.sh
 do
-   (ulimit -S -t $MAXTIME; ulimit -S -v $MAXMEM; sh $file $@ 2>&1 | diff $file.ok - >> $LOG || echo "ERROR: $file" >> $LOG; /bin/echo -n " o") &
+   (ulimit -S -t $MAXTIME; ulimit -S -m $MAXMEM; sh $file $@ 2>&1 | diff $file.ok - >> $LOG || echo "ERROR: $file" >> $LOG; /bin/echo -n " o") &
 done
 
 wait 
