avoid assuming sh and echo are at /bin, so that owl can be built on android more easily

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -40,13 +40,13 @@ touch $LOG
 
 for file in tests/*$SUFFIX.scm
 do
-   ($@ -q $file 2>&1 | grep -v SEED | diff $file.ok - >> $LOG || echo "ERROR: $file" >> $LOG; /bin/echo -n " o") &
+   ($@ -q $file 2>&1 | grep -v SEED | diff $file.ok - >> $LOG || echo "ERROR: $file" >> $LOG; echo -n " o") &
    waitnjobs $MAXJOBS
 done
 
 for file in tests/*$SUFFIX.sh
 do
-   ((sh $file $@ 2>&1 || echo "NONZERO: $file $?") | grep -v SEED | diff $file.ok - >> $LOG || echo "ERROR: $file" >> $LOG; /bin/echo -n " o") &
+   ((sh $file $@ 2>&1 || echo "NONZERO: $file $?") | grep -v SEED | diff $file.ok - >> $LOG || echo "ERROR: $file" >> $LOG; echo -n " o") &
    waitnjobs $MAXJOBS
 done
 
