added time- and memory-limits to tests/run, to make sure automatic tests do not hang

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -15,12 +15,12 @@ touch $LOG
 
 for file in tests/*.scm
 do
-   ($@ -q < $file 2>&1 | diff $file.ok - >> $LOG || echo "ERROR: $file" >> $LOG; /bin/echo -n " o") &
+   (ulimit -S -t 60; ulimit -S -v 2147483648; $@ -q < $file 2>&1 | diff $file.ok - >> $LOG || echo "ERROR: $file" >> $LOG; /bin/echo -n " o") &
 done
 
 for file in tests/*.sh
 do
-   (sh $file $@ 2>&1 | diff $file.ok - >> $LOG || echo "ERROR: $file" >> $LOG; /bin/echo -n " o") &
+   (ulimit -S -t 60; ulimit -S -v 2147483648; sh $file $@ 2>&1 | diff $file.ok - >> $LOG || echo "ERROR: $file" >> $LOG; /bin/echo -n " o") &
 done
 
 wait 
