ignoring lines with SEED in test output and logging it for math test

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -17,12 +17,12 @@ MAXMEM=1048576 # 1GB
 MAXTIME=60
 for file in tests/*.scm
 do
-   (ulimit -S -t $MAXTIME; ulimit -S -m $MAXMEM; $@ -q $file 2>&1 | diff $file.ok - >> $LOG || echo "ERROR: $file" >> $LOG; /bin/echo -n " o") &
+   (ulimit -S -t $MAXTIME; ulimit -S -m $MAXMEM; $@ -q $file 2>&1 | grep -v SEED | diff $file.ok - >> $LOG || echo "ERROR: $file" >> $LOG; /bin/echo -n " o") &
 done
 
 for file in tests/*.sh
 do
-   (ulimit -S -t $MAXTIME; ulimit -S -m $MAXMEM; sh $file $@ 2>&1 | diff $file.ok - >> $LOG || echo "ERROR: $file" >> $LOG; /bin/echo -n " o") &
+   (ulimit -S -t $MAXTIME; ulimit -S -m $MAXMEM; sh $file $@ 2>&1 | grep -v SEED | diff $file.ok - >> $LOG || echo "ERROR: $file" >> $LOG; /bin/echo -n " o") &
 done
 
 wait 
