updated some benchmarks and also measuring fasl boot time in bench/run. make-work -ish metawork, since no time to do anything useful atm :(

diff --git a/bench/run b/bench/run
--- a/bench/run
+++ b/bench/run
@@ -4,9 +4,13 @@
 # TODO: pretty autoupdating graphs to somewhere in http://haltp.org/
 # TODO: metametrics (fasl size, lines of code, etc) + how to handle in overview?
 
-BESTOF=5
+BESTOF=3
 
-# check deps in case someone tries to run this elsewhere
+# check where we are and that owl is built
+test -f c/ovm.c || { echo "Run me at owl-lisp root directory."; exit 1; }
+make
+
+# global deps
 for dep in ol time seq
 do
    test -x "/usr/bin/$dep" || { echo "I demand /usr/bin/$dep"; exit 1; }
@@ -14,38 +18,51 @@ done
 
 ulimit -S -t 600 # kill overly long running benchmark (implies broken owl or microcontroller)
 
-# cmd → print time in ms
-owltime() {
+# regex cmd ... → print time in ms
+rextime() {
+   REGEX=$1 # output must have a match
+   shift
    START=$(ol -e '(time-ms)')
-   $@ | grep -q "^OK$" || { echo "Test failed: $@"; exit 2; } # maybe should report 0 and carry on
-   ol -e "(- (time-ms) $START)"
+   $@ | grep -q $REGEX && ol -e "(- (time-ms) $START)" || echo "0" # to signal test failed
 }
 
-# bench/foo.scm → print best-of-$BESTOF time in ms
-besttime() {
-   BESTFASL=1333333337
-   BESTBIN=1333333337
+justtime() {
+   START=$(ol -e '(time-ms)')
+   $@ && ol -e "(- (time-ms) $START)" || echo "0" # to signal test failed
+}
 
+# regex command ... → print best-of-$BESTOF time in ms
+besttime() {
+   BEST=1333333337
    # fasl time
    for round in $(ol -e "(iota 0 1 $BESTOF)") # "(0" "1" "2)"
    do
-      THIS=$(owltime bin/vm fasl/ol.fasl --run $1)
-      test "$THIS" -lt "$BESTFASL" && BESTFASL="$THIS"
+      THIS=$(rextime $@)
+      test "$THIS" -lt "$BEST" && BEST="$THIS"
    done
-
-   # binary time
-   BIN="./$(echo $1 | sed 's/\.scm$//')"
-   cat $1 | bin/ol -x c -O2 -o - | gcc -x c -O2 -o $BIN -
-   for round in $(ol -e "(iota 0 1 $BESTOF)") # "(0" "1" "2)"
-   do
-      THIS=$(owltime $BIN)
-      test "$THIS" -lt "$BESTBIN" && BESTBIN="$THIS"
-   done
-
-   echo "$1: ${BESTFASL}ms fasl, ${BESTBIN}ms binary"
+   echo $BEST
 }
+
+# name bench/foo.scm -> print fasl and compiled best-of-n times
+scmtimes() {
+   NAME=$1
+   SOURCE=$2
+   BESTFASL=$(besttime "^OK$" bin/vm fasl/ol.fasl --run $SOURCE)
+   BIN="./$(echo $SOURCE | sed 's/\.scm$//')"
+   bin/ol -x c -O2 -o $BIN.c $SOURCE
+   gcc -O2 -o $BIN $BIN.c
+   BESTBIN=$(besttime "^OK$" $BIN)
+   echo "$NAME: ${BESTFASL}ms fasl, ${BESTBIN}ms binary"
+}
+
+# custom tests
+BOOTTIME=$(justtime bin/vm fasl/ol.fasl --run owl/ol.scm -s none -o tmp/out.fasl)
+echo "faslboot: ${BOOTTIME}ms"
 
 for benchmark in bench/*.scm
 do
-   besttime $benchmark
+   NAME=$(echo $benchmark | sed -e 's/bench\///' -e 's/\.scm//')
+   scmtimes $NAME $benchmark
 done
+
+
